### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DerekYu177** [DerekYu177/425G14#16]
Remaining tasks
- [x] fix ID stage architecture
- [x] have special registers (they can be signals) for HI/LO
- [ ] implement forwarding and hazard detection (LOL)
- [x] write the architecture for MEM
  - [x] have MEM stage accept the `valid_load_store` signal
- [x] write the architecture for WB
  - [x] implement `load_store` as `std_logic` pipeline registers from `ID` to `WB` (three bit signal, one for `valid`, one for `load`, and one for 'store')
  - [x] implement `store_address` as `integer` pipeline registers from `ID` to `WB`
  - [x] have ID produce `valid_load_store` flags 
  - [x] alter `pipeline.vhd` for new entity interface
  - [x] EX is the one that has to add values onto the data_store_address register, not ID. In order to do this it must consume `valid_load_store` flag from ID
  - [x] WB has to take care also of MFHI and MFLO
- [x] figure out why the f'kin `case` statement shows syntax error in the ID stage architecture
- [x] check to see if the `instruction_memory` can handle normal `pc = pc + 4` statements.
- [x] clean up the pipeline registers - there's just too many of them.

**Comment by DerekYu177** [comment]
if `load` == 1, then `ex_mem` is the address of the value to load _and then pass onto wb_. `data_store_address` then is the register that WB stores `mem_wb` into. 
if `store` == 1, then `ex_mem` is the address of the value to store. The value that is actually being stored comes from ID. Where this value comes from remains to be seen.  
if `store or load` == 0, then `ex_mem` is the value of the register that is being modified, and `data_store_address` holds the address that the register is to be stored.

**Comment by DerekYu177** [comment]
I think we should also have a common pipeline register that can hold everything, because the current implementation is ridiculous.

**Comment by DerekYu177** [comment]
Each pipeline needs at least:
1. 2x 32b bus for the main pipeline registers
2. An int which either holds pc or address
3. pc_valid
4. address_valid
5. load_valid
6. store_valid
7. store_register_valid

**Comment by DerekYu177** [comment]
I will explore this in a new PR

**Comment by DerekYu177** [comment]
For HI/LO, there remains a lot of work to be done. 
- [x] add 2x 32b outputs for `hi_data` and `low_data` to the PRB
- [x] add 2 x 1b outputs for `hi_store` and `lo_store` to the PRB
  - [x] add more internal signals
  - [x] modify each pipeline register component declaration
  - [x] propagate them internally from one section to another
  - [x] modify the WB component declaration to take them as input
  - [x] modify the WB port map 
  - [x] modify the entity 
  - [x] add functionality to the architecture
- [x] add `hi`/`lo` registers to the register file
- [x] modify `ID`, `EX` and `WB`
- [x] update readme

**Comment by DerekYu177** [comment]
- [ ] Final Report (April 11th)
- [ ] Optimized Processor (April 11th)

**Comment by DerekYu177** [comment]
So `Test 2 is broken`. Attempting to debug now.

**Comment by DerekYu177** [comment]
`Test 2` is fixed. `Test 4` is broken. Related to input delay.

**Comment by DerekYu177** [comment]
The reads are fixed #27 . There is a memory issue.

**Comment by DerekYu177** [comment]
Haven't fixed the memory issue but is it possible to optimize the output to write more than one line at a time? This would speed up the time until there is a successful output. (reduce the time from 5us).
